#!/usr/bin/env bash
make test

if [ "$(id -u)" == "0" ]; then
  echo "You don't want to commit as root" 1>&2
  exit 1
fi
echo ""
echo "Checking Coding Style"
FILES=`git diff --numstat --name-only origin/master master | grep -e .cpp$`

for x in $FILES
do
    if [ -f $x ];
    then
        vera++ -e "$x"
        OUT=$?
        if [ $OUT -eq 0 ];then
            echo "Code complies with styling conventions."
        else
            echo "Error in code style, not commiting."
            exit 1
        fi        
    else
        echo "File $x does not exist. Not checking code conventions."
    fi

done
