#!/usr/bin/perl
use Template;
use Getopt::Long;

my $className = "";
GetOptions ("class=s" => \$className)
    or die("Error in command line arguments\n");

$num_args = $#ARGV + 1;
if ($num_args != 1) {
    print "\nUsage:";
    print "\nalan generate -class=ClassName\n";
    print "\nalan blender install [blender version]\n";
    print "  Copy game data and copy the blender extension\n";
    exit;
}

if (($ARGV[0] == "generate") && !($className eq "")){
    print "\nGenerating ${className} class.\n";
    $capitalClassName = $className;
    $capitalClassName =~ s/((?<=[a-z])[A-Z][a-z]+)/_\U$1/g;
    $capitalClassName =~ s/(\b[A-Z][a-z]+)/\U$1/g;
    my %data = ( name => $className, capName => $capitalClassName);
    my $template = Template->new;
    $template->process('tools/alan/templates/hpp.tpl', \%data, "${className}.hpp") || die $template->error;
    $template->process('tools/alan/templates/cpp.tpl', \%data, "${className}.cpp") || die $template->error;    
    exit;
}

if (($ARGV[0] == "blender") && ($ARGV[1] == "install") && (defined $ARGV[2])){
    system("./tools/blender/copyGameData");
    system("./tools/blender/linkExtension -b ${ARGV[2]}");
}
 
print "\nUsage: alan command\n";
