* About
GlPortal is a puzzle game where you have to shoot portals in order
to reach the goal.

It was created by Simon Larsen in 2012 and I took over in 2013.

If you need to talk directly to me (everything that is no bug report,
feature request or question that fits in the public discussion)
you can contact me at portal at w3-net.de by email.

You can find the website at http://glportal.de .

Chat with us at irc.freenode.org in the channel ##glportal.
* Contributors
** Programming
- Henry Hirsch
- Julian Thijssen
** Graphics
- Urpo Lankinen - Bitmap Font
- Kuronus for Blendswap - FPS Hands rigged (added portal egg)
- Jason Pulkkinen - GlPortal logo
* Compile the source
For instructions on how to compile the game please read COMPILE.org.
* Join the team
You can join the community at http://glportal.de/groups/glportal/ 
for questions and discussions about the development of the game.
A makeshift Issue tracker can be found at 
https://github.com/hhirsch/glPortal/issues .

Please send me a pull request on github if you have changes.
