#+BEGIN_HTML
<a href="http://jenkins.glportal.de/job/GlPortal/"><img src="http://jenkins.glportal.de/buildStatus/icon?job=GlPortal"></a>
#+END_HTML

* About
GlPortal is a puzzle game where you have to use teleportation to reach the exit.

GlPortal was created by Simon Larsen in 2012 and Henry Hirsch took over development in 2013.
In 2014 Julian Thijssen joined the development team.

You can find the website at http://glportal.de .

Chat with us at irc.freenode.org in the channel ##glportal.
* Contributors
** Programming
- Henry Hirsch
- Julian Thijssen
- Dorian Wouters
- Juraj Oravec
- Stephan Vedder
- Xantares
** Graphics
- Urpo Lankinen - Bitmap Font
- Kuronus for Blendswap - FPS Hands rigged (added portal egg)
- Jason Pulkkinen - GlPortal logo
* Compile the source
For instructions on how to compile the game please read COMPILE.org.
* Join the team
Chat with us at irc.freenode.org in the channel ##glportal
for questions and discussions about the development of the game.
Report Issues to http://bugs.glportal.de .

Please send me a pull request on github if you have changes.
