CFLAGS		:= -Wall -Os -O3
CXXFLAGS	:= $(CFLAGS) `pkg-config --cflags freetype2`
LDFLAGS		:= -lm `pkg-config --libs freetype2`
SOURCES		:= BinPacker.cpp lodepng.cpp main.cpp stb_image.c
OBJS		:= $(patsubst %.cpp,%.o,$(SOURCES:.c=.o))
EXE		:= SDFont

.PHONY: all
all: $(EXE)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(EXE): $(OBJS)
	$(CXX) $(OBJS) $(LDFLAGS) -o $@

.PHONY: clean
clean:
	 -$(RM) -rf $(OBJS) $(EXE)