set(VHACD_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/vhacd-lib")
set(VHACD_INCLUDE_DIR "${VHACD_ROOT_DIR}/public")
set(VHACD_INCLUDE_DIRS ${VHACD_INCLUDE_DIR})
set(VHACD_LIBRARY "VHACD_LIB")
set(VHACD_LIBRARIES ${VHACD_LIBRARY})

set(NO_OPENCL ON)
set(NO_OPENMP ON)
add_subdirectory("${VHACD_ROOT_DIR}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(VHACD DEFAULT_MSG VHACD_LIBRARIES VHACD_INCLUDE_DIR VHACD_INCLUDE_DIRS)

mark_as_advanced(VHACD_LIBRARY VHACD_LIBRARIES VHACD_INCLUDE_DIR VHACD_INCLUDE_DIRS)
