set(DUKTAPE_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external")
set(DUKTAPE_INCLUDE_DIRS ${DUKTAPE_INCLUDE_DIR})
set(DUKTAPE_LIBRARY "Duktape")
set(DUKTAPE_LIBRARIES ${DUKTAPE_LIBRARY})

add_subdirectory("${DUKTAPE_INCLUDE_DIR}/duktape")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args ( Duktape
  DEFAULT_MSG DUKTAPE_LIBRARIES DUKTAPE_INCLUDE_DIR DUKTAPE_INCLUDE_DIRS
)

mark_as_advanced(DUKTAPE_LIBRARY DUKTAPE_LIBRARIES DUKTAPE_INCLUDE_DIR DUKTAPE_INCLUDE_DIRS)
